version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    ports:
      - 5000:5000
    env_file:
      - /backend/.env
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    ports:
      - 5173:5173
    depends_on:
      - api
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
